- App.js
- babel.config.js
- lib/apollo.js
- package.json
- screens/home/index.js
- utils/get_env.js
- yarn.lock
- Initial Setup for Apollo Client to use Graphql Hooks, Queries, Mutations, and Subscriptions
> feat: Setup Apollo

- context/user.js
- screens/account/index.js
- screens/login/otp/index.js
- utils/useSession.js
- Created Logout Functionality
- Update User Details in Context when the user logs in
> fix: update user info on login & logout

- App.js
- components/product.js
- Open the Location selector when a user tries to add an item to the cart and the location is not selected.
> fix: open location selector when user try add to cart and location is not selected

- screens/menu/index.js
- Make the Products list scrollable and Scroll to specific elements when a category is chosen
> feat: scroll products to specific category

- components/modifierPopup.js
- components/product.js
- Show Counter on Product Card when that product is added to the cart
- Implement `I will choose` and `repeat last one`  functionality for this counter
> feat: counter button on product card

- screens/fulfillment/index.js
- The fulfillment Options label will be coming from DB from orderTabs
> fix: fulfillment options label taken from DB from orderTabs

- brandConfig.json
- screens/login/otp/index.js
- Made skip button visibility on login page config based
> fix: made skip button visibility on login page config based

- assets/loaders/index.js
- assets/loaders/spinner.js
- components/location/locationSelector.js
- components/modifierPopup.js
- components/payButton.js
- components/paymentOptionRenderer.js
- components/product.js
- lib/payment.js
- navigation/index.js
- screens/account/index.js
- screens/account/subscreen/loyaltyScreen.js
- screens/account/subscreen/offers.js
- screens/account/subscreen/wallet.js
- screens/cart/cartCard.js
- screens/cart/index.js
- screens/login/index.js
- screens/menu/index.js
- screens/myOrders/index.js
- screens/myOrders/subscreen/orderDetail.js
- screens/myOrders/subscreen/orderTracking.js
- screens/product/index.js
- Added Loaders on all Screens
- Added a New SafeAreaView Component instead of the built-in one as we are using the `react-native-safe-area-context` on some screens
- Added `flex: 1` style to SafeAreaView Component of `react-native-safe-area-context`
> feat: added loaders on all screens

- graphql/subscriptions.js
- screens/myOrders/subscreen/orderDetail.js
- Updated Subscription GraphQL Query to fetch User's Orders to get the Orders in a format where orders which have null createdAt will be at last
- Wrapped Order Details Page into Safe Area View Component
> fix: Updated subscription query for My Orders page, to fetch null createdAt orders will be at last

- assets/loaders/spinner.js
- screens/login/otp/index.js
- screens/login/otp/mobileNumberForm.js
- screens/login/otp/otpForm.js
- Added Loading States in buttons of the Login flow
- Fix Incorrect OTP error message
> tweak: added loading states into login flow

- graphql/queries.js
- graphql/subscriptions.js
- lib/config.js
- utils/get_env.js
- Used Query instead of subscription to fetch app config
- Made Brand Domain env based
> fix: get app settings with query instead of subscription, and made brand domain env based

- components/authScreenLogin.js
- package-lock.json
- screens/account/subscreen/loyaltyScreen.js
- screens/account/subscreen/wallet.js
- screens/fulfillment/index.js
- screens/login/otp/index.js
- screens/login/otp/mobileNumberForm.js
- screens/login/otp/otpForm.js
- screens/product/index.js
- yarn.lock
Change font to Metropolis in all screens
> Change font to Metropolis in all screens

- components/button.js
- components/floatingMenu.js
- screens/menu/index.js
- change floating menu position
> tweak: change floating menu button position

- components/location/delivery.js
- components/location/googlePlaceAutoComplete.js
- components/location/userAddressList.js
- context/index.js
- screens/refineLocation/index.js
- Added Saved Address Selection Functionality into Location Selector
> feat: added users saved address list into Location Selector

- components/product.js
- context/onDemandMenu.js
- package.json
- screens/menu/index.js
- yarn.lock
- Move Product Fetching Query into Menu Context
- Added Caching for Images
> tweak: fetch prdoucts in context

- screens/cart/cartCard.js
- screens/product/index.js
- Added Default image to cart page
- Fix Product price on Product Page
> fix: added default image

- components/userInfo.js
- graphql/mutations.js
- screens/cart/address.js
- screens/cart/fulfillmentSection/Delivery.js
- screens/cart/fulfillmentSection/Pickup.js
- screens/cart/index.js
- screens/refineLocation/index.js
- Optimistic Response to user Info
- Optimistic Response to Address
- Optimistic Response to Fulfillment
> feat: optimistic response on user info, fulfillment info, address

- assets/loaders/productsLoader.js
- components/modifierPopup.js
- components/skeleton.js
- screens/cart/cartCard.js
- screens/home/index.js
- screens/product/index.js
- Change Modal Modifiers into Bottom Sheet
- Added Skeleton for Trending Products on Home Screen
> fix: change modal modifiers into bottom sheets, and added skeleton into trending products

- components/cacheVideo.js
- package.json
- screens/home/promotionCarousel.js
- Added video caching functionality
> feat: added video caching functionality

- components/paymentOptionRenderer.js
- components/paymentProcessingModal.js
- graphql/subscriptions.js
- screens/account/subscreen/wallet.js
- utils/getRazorpayOptions.js
> fix: split razorpay payment methods into diffrent payment options

- components/location/delivery.js
- components/location/locationSelector.js
- components/location/pickup.js
- components/location/storeList.js
- components/product.js
- screens/refineLocation/index.js
> fix: redirected to product after setting location with which location selector was opened

- components/location/googlePlaceAutoComplete.js
> fix: prev address remains in searchbar after clicking on my location button

- components/modifierPopup.js
- components/paymentProcessingModal.js
- components/product.js
- components/userInfo.js
- screens/account/index.js
- screens/cart/address.js
- screens/cart/cartCard.js
- screens/cart/cartItemList.js
- screens/login/otp/mobileNumberForm.js
- screens/login/otp/otpForm.js
- screens/product/index.js
> Fix/fix UI issues
